name: Verify Docs
on: [push, pull_request]

jobs:
  verify-docs:
    name: Verify docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Generate docs
        run: go generate

      - name: Check if git detects no changes
        run: |
          if output=$(git status --porcelain) && [ -z "$output" ]; then
            echo "Docs are up to date";
          else
            echo "Not all docs are up-to-date. Run 'go generate' and commit the changes.";
            echo $output;
            exit 1;
          fi
